package com.helloanwar.mvvmate.core.ai

import com.helloanwar.mvvmate.core.UiAction

/**
 * Handles converting raw text (e.g., JSON, XML, or raw commands generated by an LLM)
 * into a typed Kotlin [UiAction].
 * 
 * Implement this interface using your preferred serialization framework 
 * (e.g., kotlinx.serialization, Gson, Moshi) to map LLM tool outputs to Kotlin sealed classes.
 */
interface AiActionParser<A : UiAction> {
    
    /**
     * Parses a raw string command into the domain-specific action.
     * 
     * @param rawCommand The text generated by the AI agent (e.g. `{"type": "Increment"}`).
     * @return The parsed [UiAction].
     * @throws Exception if the string cannot be parsed into a valid action.
     */
    @Throws(Exception::class)
    fun parse(rawCommand: String): A
}
